// Curated Digital SAT high-utility vocabulary bank.
// Categories mirror how Words in Context / transitions actually test words
// (function in argument), not dictionary alphabetization.
// Optional `cb_question_id` can be added later to link official WIC stems.

import type { VocabCategory, VocabEntry } from "./types";

function e(
  id: string,
  word: string,
  definition: string,
  category: VocabCategory,
  passage: string,
  choices: [string, string, string, string],
  correctIndex: 0 | 1 | 2 | 3,
  tip?: string,
): VocabEntry {
  return { id, word, definition, category, passage, choices, correctIndex, tip };
}

export const VOCAB_BANK: VocabEntry[] = [
  // ── Argument & evidence ──────────────────────────────────────────
  e("arg-assert", "assert", "state strongly as true", "argument",
    "The historian _____ that the treaty was signed under duress, citing letters from both ambassadors.",
    ["asserts", "concedes", "obscures", "postpones"], 0),
  e("arg-contend", "contend", "argue; claim as true", "argument",
    "Critics _____ that the study's sample was too small to support such a sweeping conclusion.",
    ["contend", "omit", "decorate", "postpone"], 0),
  e("arg-maintain", "maintain", "continue to claim; uphold a position", "argument",
    "Despite new criticism, the researcher continues to _____ that the original findings remain valid.",
    ["maintain", "discard", "invent", "delay"], 0),
  e("arg-concede", "concede", "admit a point (often while holding another view)", "argument",
    "She _____ that the reform will be expensive, yet argues the long-term benefits outweigh the cost.",
    ["concedes", "denies", "celebrates", "ignores"], 0,
    "Concede = admit a point, not abandon the whole argument."),
  e("arg-acknowledge", "acknowledge", "recognize as true or valid", "argument",
    "The authors _____ several limitations of their method before presenting the main results.",
    ["acknowledge", "conceal", "fabricate", "ridicule"], 0),
  e("arg-imply", "imply", "suggest without stating directly", "argument",
    "The data do not prove causation, but they _____ a strong association between sleep and test scores.",
    ["imply", "refute", "erase", "mandate"], 0),
  e("arg-infer", "infer", "conclude from evidence", "argument",
    "From the map's missing labels, readers can _____ that the cartographer lacked complete surveys.",
    ["infer", "invent", "ignore", "dictate"], 0),
  e("arg-substantiate", "substantiate", "support with evidence", "argument",
    "Without additional measurements, the team could not _____ its claim about rising ocean temperatures.",
    ["substantiate", "discard", "parody", "delay"], 0),
  e("arg-corroborate", "corroborate", "confirm with independent evidence", "argument",
    "A second lab's results _____ the first team's findings, increasing confidence in the conclusion.",
    ["corroborate", "contradict", "omit", "mock"], 0),
  e("arg-validate", "validate", "confirm accuracy or legitimacy", "argument",
    "The controlled trial was designed to _____ the drug's effectiveness against a placebo.",
    ["validate", "obscure", "postpone", "ridicule"], 0),
  e("arg-refute", "refute", "disprove decisively", "argument",
    "New fossil evidence appears to _____ the older theory that the species never left Africa.",
    ["refute", "endorse", "decorate", "summarize"], 0),
  e("arg-rebut", "rebut", "argue against (counter without fully disproving)", "argument",
    "In the final paragraph, the author tries to _____ the main objection raised by earlier critics.",
    ["rebut", "celebrate", "ignore", "plagiarize"], 0),
  e("arg-contradict", "contradict", "assert the opposite of", "argument",
    "Later measurements _____ the initial report that the river had completely dried up.",
    ["contradict", "confirm", "illustrate", "praise"], 0),
  e("arg-undermine", "undermine", "weaken gradually or indirectly", "argument",
    "Inconsistencies in the witness statements _____ the prosecution's timeline of events.",
    ["undermine", "strengthen", "celebrate", "publish"], 0),
  e("arg-challenge", "challenge", "question the validity of", "argument",
    "Several economists _____ the assumption that lower taxes automatically raise employment.",
    ["challenge", "copy", "delay", "decorate"], 0),
  e("arg-reinforce", "reinforce", "strengthen; support further", "argument",
    "The case study _____ the broader claim that early reading programs improve later scores.",
    ["reinforces", "weakens", "ignores", "confuses"], 0),
  e("arg-bolster", "bolster", "support strongly", "argument",
    "Archival letters _____ her argument that the inventor knew of prior designs.",
    ["bolster", "undermine", "erase", "mock"], 0),
  e("arg-buttress", "buttress", "reinforce with evidence or reasoning", "argument",
    "Cited experiments _____ the claim that the catalyst works only at high temperatures.",
    ["buttress", "refute", "omit", "postpone"], 0),
  e("arg-attest", "attest", "provide evidence of; bear witness to", "argument",
    "The diaries _____ to the hardships settlers faced during the first winter.",
    ["attest", "object", "invent", "delay"], 0),
  e("arg-endorse", "endorse", "publicly support or approve", "argument",
    "The committee refused to _____ the proposal until safety data were released.",
    ["endorse", "hide", "plagiarize", "delay only"], 0),

  // ── Analysis & evaluation ────────────────────────────────────────
  e("an-scrutinize", "scrutinize", "examine closely and carefully", "analysis",
    "Editors _____ every source note before the article goes to print.",
    ["scrutinize", "ignore", "celebrate", "postpone"], 0),
  e("an-assess", "assess", "evaluate; judge the quality or amount of", "analysis",
    "The panel will _____ whether the new curriculum meets state standards.",
    ["assess", "discard", "imitate", "delay"], 0),
  e("an-critique", "critique", "evaluate critically", "analysis",
    "The review _____ the film's pacing while praising its cinematography.",
    ["critiques", "ignores", "copies", "funds"], 0),
  e("an-appraise", "appraise", "judge the value or quality of", "analysis",
    "Collectors _____ the painting based on condition, provenance, and rarity.",
    ["appraise", "destroy", "hide", "postpone"], 0),
  e("an-gauge", "gauge", "measure or estimate", "analysis",
    "Polls are used to _____ public support for the proposed regulation.",
    ["gauge", "suppress", "invent", "decorate"], 0),
  e("an-diagnose", "diagnose", "identify the nature or cause of a problem", "analysis",
    "Economists try to _____ why housing costs rose faster than wages.",
    ["diagnose", "celebrate", "ignore", "fabricate"], 0),
  e("an-probe", "probe", "investigate thoroughly", "analysis",
    "Journalists _____ the company's financial records after the whistleblower's report.",
    ["probed", "decorated", "postponed", "celebrated"], 0),
  e("an-weigh", "weigh", "consider carefully, especially trade-offs", "analysis",
    "The author _____ the benefits of urban density against the costs of congestion.",
    ["weighs", "ignores", "invents", "delays"], 0),
  e("an-synthesize", "synthesize", "combine parts into a coherent whole", "analysis",
    "The literature review _____ findings from dozens of experiments into one model.",
    ["synthesizes", "discards", "mocks", "hides"], 0),
  e("an-interpret", "interpret", "explain the meaning of", "analysis",
    "Scholars _____ the poem's final stanza in strikingly different ways.",
    ["interpret", "erase", "fund", "postpone"], 0),
  e("an-illuminate", "illuminate", "clarify; make understandable", "analysis",
    "The case study _____ how small incentives can change voting behavior.",
    ["illuminates", "obscures", "postpones", "ridicules"], 0),
  e("an-elucidate", "elucidate", "make clear; explain", "analysis",
    "The introduction _____ key terms so non-specialists can follow the argument.",
    ["elucidates", "confuses", "hides", "delays"], 0),
  e("an-dissect", "dissect", "analyze in detail", "analysis",
    "The critic carefully _____ the speech's rhetorical strategies.",
    ["dissects", "ignores", "funds", "copies"], 0),
  e("an-calibrate", "calibrate", "adjust precisely; set standards carefully", "analysis",
    "Researchers _____ their instruments before each trial to reduce measurement error.",
    ["calibrate", "discard", "decorate", "postpone"], 0),

  // ── Tone & attitude ──────────────────────────────────────────────
  e("to-skeptical", "skeptical", "doubtful; not easily convinced", "tone",
    "The reviewer takes a _____ stance toward the company's optimistic forecast.",
    ["skeptical", "gushing", "indifferent only", "celebratory"], 0),
  e("to-dismissive", "dismissive", "showing that something is unworthy of consideration", "tone",
    "His _____ reply suggested he did not take the safety concerns seriously.",
    ["dismissive", "respectful", "curious", "grateful"], 0),
  e("to-cautious", "cautious", "careful; avoiding risk or overstatement", "tone",
    "The scientists remained _____, noting that one study cannot settle the debate.",
    ["cautious", "triumphant", "sarcastic", "indifferent"], 0),
  e("to-measured", "measured", "carefully controlled; moderate in tone", "tone",
    "In a _____ response, the mayor acknowledged mistakes without attacking opponents.",
    ["measured", "hysterical", "flippant", "silent"], 0),
  e("to-ambivalent", "ambivalent", "having mixed or conflicting feelings", "tone",
    "Voters seemed _____ about the plan: supportive of its goals, uneasy about its cost.",
    ["ambivalent", "unanimous", "jubilant", "apathetic only"], 0),
  e("to-equivocal", "equivocal", "ambiguous; open to more than one interpretation", "tone",
    "The spokesperson's _____ answers left reporters unsure whether the project would continue.",
    ["equivocal", "blunt", "cheerful", "silent"], 0),
  e("to-enthusiastic", "enthusiastic", "showing intense interest or eagerness", "tone",
    "The curator was _____ about the exhibition, calling it the museum's most ambitious show yet.",
    ["enthusiastic", "hostile", "bored", "suspicious"], 0),
  e("to-polemical", "polemical", "strongly critical or controversial in argument", "tone",
    "The essay's _____ style attacks rivals more than it explains the policy itself.",
    ["polemical", "neutral", "playful", "timid"], 0),
  e("to-sardonic", "sardonic", "grimly mocking; cynical humor", "tone",
    "With a _____ remark, she questioned whether the 'reform' would change anything at all.",
    ["sardonic", "sincere", "naive", "joyful"], 0),
  e("to-dispassionate", "dispassionate", "not influenced by strong emotion; impartial", "tone",
    "The report aims for a _____ analysis of the data rather than a call to protest.",
    ["dispassionate", "fiery", "sentimental", "flippant"], 0),
  e("to-candid", "candid", "frank; honest and direct", "tone",
    "In a _____ interview, the CEO admitted the product launch had been rushed.",
    ["candid", "evasive", "hostile", "silent"], 0),
  e("to-trenchant", "trenchant", "incisive; sharply effective in criticism", "tone",
    "Her _____ critique exposed weaknesses the earlier reviews had missed.",
    ["trenchant", "vague", "flattering", "lengthy only"], 0),
  e("to-didactic", "didactic", "intended to teach, sometimes overly so", "tone",
    "Some readers found the novel too _____, more lecture than story.",
    ["didactic", "plotless only", "silent", "humorous only"], 0),
  e("to-restrained", "restrained", "held back; not excessive", "tone",
    "The judge's _____ language avoided drama while still condemning the misconduct.",
    ["restrained", "bombastic", "hysterical", "flippant"], 0),

  // ── Change & development ─────────────────────────────────────────
  e("ch-evolve", "evolve", "develop gradually", "change",
    "Over decades, the city's zoning rules _____ to allow denser housing near transit.",
    ["evolved", "froze only", "vanished", "copied"], 0),
  e("ch-transform", "transform", "change thoroughly in form or nature", "change",
    "Digitization has _____ how archives are searched and shared.",
    ["transformed", "ignored", "delayed", "hidden"], 0),
  e("ch-adapt", "adapt", "adjust to new conditions", "change",
    "Species that can _____ to warmer climates may outcompete those that cannot.",
    ["adapt", "refuse", "vanish only", "freeze"], 0),
  e("ch-revise", "revise", "change after reconsideration", "change",
    "The authors _____ their model after reviewers pointed out a flawed assumption.",
    ["revised", "published only", "hid", "copied"], 0),
  e("ch-modify", "modify", "alter slightly or partially", "change",
    "Engineers _____ the design to reduce noise without changing its power output.",
    ["modified", "abandoned", "celebrated", "ignored"], 0),
  e("ch-supplant", "supplant", "replace, often by force or superiority", "change",
    "Streaming services largely _____ physical media as the default way people watch films.",
    ["supplanted", "ignored", "funded", "copied"], 0),
  e("ch-proliferate", "proliferate", "increase rapidly in number", "change",
    "As smartphones _____, public libraries expanded digital lending programs.",
    ["proliferated", "vanished", "froze", "shrank only"], 0),
  e("ch-stagnate", "stagnate", "stop developing; become inactive", "change",
    "Without new investment, wages in the sector began to _____.",
    ["stagnate", "soar", "diversify", "stabilize only"], 0),
  e("ch-erode", "erode", "wear away gradually", "change",
    "Years of scandals _____ public trust in the agency.",
    ["eroded", "strengthened", "created", "funded"], 0),
  e("ch-accelerate", "accelerate", "speed up", "change",
    "Cheaper sensors _____ the adoption of remote environmental monitoring.",
    ["accelerated", "halted", "hid", "ignored"], 0),
  e("ch-diminish", "diminish", "become or make smaller", "change",
    "As competition grew, the company's market share began to _____.",
    ["diminish", "expand", "stabilize only", "appear"], 0),
  e("ch-fluctuate", "fluctuate", "rise and fall irregularly", "change",
    "Oil prices _____ throughout the year in response to weather and geopolitics.",
    ["fluctuated", "froze", "vanished", "stayed fixed"], 0),
  e("ch-wane", "wane", "decrease in strength or intensity", "change",
    "Interest in the fad began to _____ once cheaper alternatives appeared.",
    ["wane", "surge", "begin", "stabilize only"], 0),
  e("ch-burgeon", "burgeon", "grow or expand rapidly", "change",
    "A _____ tech sector drew workers from nearby manufacturing towns.",
    ["burgeoning", "shrinking", "frozen", "hidden"], 0),

  // ── Importance & value ───────────────────────────────────────────
  e("im-paramount", "paramount", "more important than anything else", "importance",
    "For the negotiators, protecting civilians was of _____ concern.",
    ["paramount", "minor", "decorative", "optional"], 0),
  e("im-pivotal", "pivotal", "of crucial importance; turning-point", "importance",
    "The discovery of the letter was _____ to rewriting the inventor's biography.",
    ["pivotal", "irrelevant", "amusing", "secondary only"], 0),
  e("im-seminal", "seminal", "highly original and influential", "importance",
    "Her _____ paper shaped decades of research on memory and learning.",
    ["seminal", "obscure", "flawed only", "brief only"], 0),
  e("im-consequential", "consequential", "important; having significant effects", "importance",
    "The court issued a _____ ruling that reshaped privacy law nationwide.",
    ["consequential", "trivial", "humorous", "temporary only"], 0),
  e("im-salient", "salient", "most noticeable or important", "importance",
    "The most _____ feature of the design is its extreme energy efficiency.",
    ["salient", "hidden", "irrelevant", "decorative only"], 0),
  e("im-integral", "integral", "essential to completeness", "importance",
    "Peer review is an _____ part of how scientific claims are vetted.",
    ["integral", "optional", "decorative", "harmful"], 0),
  e("im-indispensable", "indispensable", "absolutely necessary", "importance",
    "Reliable maps were _____ to the explorers' safe return.",
    ["indispensable", "optional", "decorative", "harmful"], 0),
  e("im-foundational", "foundational", "serving as a base or starting point", "importance",
    "Basic arithmetic is _____ to later work in algebra and statistics.",
    ["foundational", "irrelevant", "advanced only", "optional"], 0),
  e("im-peripheral", "peripheral", "of secondary importance; on the edge", "importance",
    "The biography treats the inventor's hobbies as _____ to the main story.",
    ["peripheral", "central", "decisive", "foundational"], 0),
  e("im-negligible", "negligible", "so small as to be unimportant", "importance",
    "The difference between the two methods was _____, well within measurement error.",
    ["negligible", "enormous", "decisive", "unknown"], 0),
  e("im-ancillary", "ancillary", "providing support; secondary", "importance",
    "Charts and tables play an _____ role, clarifying claims made in the text.",
    ["ancillary", "primary", "hostile", "illegal"], 0),

  // ── Description ──────────────────────────────────────────────────
  e("de-multifaceted", "multifaceted", "having many aspects", "description",
    "Poverty is a _____ problem involving wages, health, and education.",
    ["multifaceted", "simple", "solved", "imaginary"], 0),
  e("de-intricate", "intricate", "very complicated or detailed", "description",
    "The clock's _____ mechanism took decades for artisans to perfect.",
    ["intricate", "crude", "broken only", "simple"], 0),
  e("de-nuanced", "nuanced", "subtle; having fine distinctions", "description",
    "A _____ reading of the treaty shows compromises on both sides.",
    ["nuanced", "simplistic", "hostile", "silent"], 0),
  e("de-prosaic", "prosaic", "ordinary; lacking poetic beauty", "description",
    "Behind the heroic myth lay a more _____ explanation: better supply lines.",
    ["prosaic", "romantic", "impossible", "mythical"], 0),
  e("de-pervasive", "pervasive", "spreading widely throughout", "description",
    "Smartphones have become so _____ that few public spaces remain device-free.",
    ["pervasive", "rare", "illegal", "temporary"], 0),
  e("de-nascent", "nascent", "just beginning to develop", "description",
    "The _____ industry still lacked standards for safety testing.",
    ["nascent", "mature", "defunct", "illegal"], 0),
  e("de-rudimentary", "rudimentary", "basic; not highly developed", "description",
    "Early calculators offered only _____ functions compared with modern computers.",
    ["rudimentary", "advanced", "useless only", "decorative"], 0),
  e("de-conspicuous", "conspicuous", "clearly visible; attracting attention", "description",
    "The tower is a _____ landmark on the skyline.",
    ["conspicuous", "hidden", "imaginary", "temporary"], 0),
  e("de-stark", "stark", "severe or bare in appearance; sharply clear", "description",
    "The report draws a _____ contrast between rich and poor neighborhoods.",
    ["stark", "blurred", "cheerful", "minor"], 0),
  e("de-fleeting", "fleeting", "lasting only a short time", "description",
    "Fame for the viral video proved _____; within a week attention had moved on.",
    ["fleeting", "permanent", "profitable only", "illegal"], 0),
  e("de-enduring", "enduring", "lasting over a long time", "description",
    "The novel's _____ popularity suggests themes that still resonate.",
    ["enduring", "brief", "accidental only", "local only"], 0),
  e("de-unassuming", "unassuming", "modest; not pretentious", "description",
    "Despite his fame, he kept an _____ manner in interviews.",
    ["unassuming", "arrogant", "hostile", "theatrical"], 0),

  // ── Precision & rigor ────────────────────────────────────────────
  e("pr-precise", "precise", "exact; accurate", "precision",
    "The recipe requires _____ measurements; small errors ruin the reaction.",
    ["precise", "rough", "optional", "decorative"], 0),
  e("pr-exacting", "exacting", "making great demands; strict", "precision",
    "The editor was _____, rejecting any footnote that lacked a full citation.",
    ["exacting", "careless", "cheerful", "silent"], 0),
  e("pr-rigorous", "rigorous", "extremely thorough and accurate", "precision",
    "A _____ experimental design separates coincidence from real effects.",
    ["rigorous", "casual", "biased only", "brief"], 0),
  e("pr-meticulous", "meticulous", "showing great attention to detail", "precision",
    "The archivist was _____ in preserving fragile documents.",
    ["meticulous", "careless", "hasty", "hostile"], 0),
  e("pr-scrupulous", "scrupulous", "careful about ethics or accuracy", "precision",
    "A _____ journalist double-checks quotes before publication.",
    ["scrupulous", "reckless", "lazy", "biased only"], 0),
  e("pr-tentative", "tentative", "not certain or fixed; provisional", "precision",
    "The researchers offered only a _____ explanation, pending more data.",
    ["tentative", "definitive", "false", "celebrated"], 0,
    "On the DSAT, tentative often beats stronger-sounding synonyms when evidence is limited."),
  e("pr-provisional", "provisional", "arranged for the present; may change", "precision",
    "The city issued a _____ permit while the full review was completed.",
    ["provisional", "permanent", "illegal", "decorative"], 0),
  e("pr-unequivocal", "unequivocal", "leaving no doubt; clear", "precision",
    "The lab's results provided _____ evidence that the compound was toxic.",
    ["unequivocal", "ambiguous", "weak", "missing"], 0),
  e("pr-robust", "robust", "strong; unlikely to fail under stress", "precision",
    "The findings remained _____ even when the team removed outliers.",
    ["robust", "fragile", "false", "unknown"], 0),
  e("pr-compelling", "compelling", "convincing; hard to dismiss", "precision",
    "The combination of archival and DNA evidence makes a _____ case for the identification.",
    ["compelling", "weak", "irrelevant", "humorous"], 0),
  e("pr-granular", "granular", "fine-grained; highly detailed", "precision",
    "The dataset is unusually _____, recording temperature every minute.",
    ["granular", "vague", "fake", "annual only"], 0),

  // ── Transitions (phrase-level, high DSAT yield) ──────────────────
  e("tr-however", "however", "marks contrast with the previous idea", "transitions",
    "The first trial failed. _____, a redesigned protocol produced clear results.",
    ["However", "Likewise", "For example", "In addition"], 0),
  e("tr-nevertheless", "nevertheless", "in spite of that; still", "transitions",
    "The climb was dangerous; _____, the team reached the summit before nightfall.",
    ["nevertheless", "similarly", "for instance", "namely"], 0),
  e("tr-therefore", "therefore", "as a logical result", "transitions",
    "The sample was contaminated; _____, the measurements could not be trusted.",
    ["therefore", "meanwhile", "for example", "by contrast"], 0),
  e("tr-consequently", "consequently", "as a result", "transitions",
    "Funding was cut; _____, the clinic reduced its hours.",
    ["consequently", "likewise", "for instance", "in particular"], 0),
  e("tr-furthermore", "furthermore", "in addition; moreover", "transitions",
    "The plan is expensive. _____, it requires staff the district does not have.",
    ["Furthermore", "However", "By contrast", "For example"], 0),
  e("tr-moreover", "moreover", "in addition to what has been said", "transitions",
    "The policy is unpopular. _____, early data suggest it is ineffective.",
    ["Moreover", "Nevertheless", "Conversely", "For instance"], 0),
  e("tr-conversely", "conversely", "in an opposite way", "transitions",
    "Urban parks raise nearby property values. _____, industrial sites often lower them.",
    ["Conversely", "Similarly", "For example", "Indeed"], 0),
  e("tr-likewise", "likewise", "in the same way; also", "transitions",
    "Birds use magnetic cues to navigate; some sea turtles _____ rely on Earth's magnetic field.",
    ["likewise", "however", "instead", "nevertheless"], 0),
  e("tr-specifically", "specifically", "in a precise or particular way", "transitions",
    "Several factors slowed growth—_____, high interest rates and weak demand abroad.",
    ["specifically", "however", "nevertheless", "conversely"], 0),
  e("tr-indeed", "indeed", "emphasizes or confirms a point", "transitions",
    "The design is efficient; _____, it uses half the energy of the previous model.",
    ["indeed", "however", "by contrast", "for example only"], 0),
  e("tr-admittedly", "admittedly", "concedes a point before continuing", "transitions",
    "_____, the sample is small, but the pattern matches larger national surveys.",
    ["Admittedly", "Consequently", "Furthermore", "Namely"], 0),
  e("tr-by-contrast", "by contrast", "introduces a clear comparison difference", "transitions",
    "Coastal towns gained population. _____, inland farming counties continued to shrink.",
    ["By contrast", "Likewise", "For example", "In addition"], 0),

  // ── Multiple meanings ────────────────────────────────────────────
  e("mm-novel", "novel", "new and original (not the book)", "multi-meaning",
    "Engineers proposed a _____ approach that abandoned traditional materials entirely.",
    ["novel", "lengthy", "fictional", "expensive only"], 0,
    "On the SAT, novel almost always means 'new,' not 'book.'"),
  e("mm-critical", "critical", "crucial (not merely disapproving)", "multi-meaning",
    "Timing was _____: the vaccine had to be stored cold within hours of production.",
    ["critical", "optional", "humorous", "literary"], 0),
  e("mm-sound", "sound", "valid or reliable (not noise)", "multi-meaning",
    "Although popular, the argument is not _____; it confuses correlation with cause.",
    ["sound", "loud", "musical", "noisy"], 0),
  e("mm-reserve", "reserve", "restraint in manner (not a stockpile)", "multi-meaning",
    "She spoke with characteristic _____, carefully avoiding exaggeration.",
    ["reserve", "volume", "anger", "humor only"], 0),
  e("mm-abstract", "abstract", "theoretical; not concrete", "multi-meaning",
    "The lecture moved from _____ principles to concrete classroom examples.",
    ["abstract", "painted", "brief", "illegal"], 0),
  e("mm-concrete", "concrete", "specific and definite (not building material)", "multi-meaning",
    "The proposal lacks _____ steps for measuring success.",
    ["concrete", "cement", "vague only", "illegal"], 0),
  e("mm-discipline", "discipline", "a field of study", "multi-meaning",
    "Economics as a _____ has expanded far beyond markets for physical goods.",
    ["discipline", "punishment", "hobby", "sport"], 0),
  e("mm-minute", "minute", "extremely small (my-NOOT)", "multi-meaning",
    "Even _____ changes in temperature can alter the crystal structure.",
    ["minute", "hourly", "brief only", "loud"], 0),
  e("mm-address", "address", "deal with; take up (not a street location)", "multi-meaning",
    "The final chapter _____ objections critics raised about the method.",
    ["addresses", "mails", "ignores", "locates"], 0),
  e("mm-attribute", "attribute", "regard as caused by", "multi-meaning",
    "Researchers _____ the score gains to longer instructional time, not new software.",
    ["attribute", "deny", "hide", "sell"], 0),
  e("mm-table", "table", "postpone consideration of (legislative sense)", "multi-meaning",
    "The committee voted to _____ the motion until more data arrived.",
    ["table", "furniture", "publish", "celebrate"], 0),
  e("mm-plant", "plant", "place secretly; establish", "multi-meaning",
    "Investigators alleged that someone tried to _____ false evidence at the scene.",
    ["plant", "water", "factory", "grow only"], 0),

  // ── Domain (science / social science) ────────────────────────────
  e("do-empirical", "empirical", "based on observation or experiment", "domain",
    "The claim rests on _____ data collected over ten field seasons.",
    ["empirical", "imaginary", "religious", "poetic only"], 0),
  e("do-hypothesis", "hypothesis", "testable proposed explanation", "domain",
    "Their _____ predicted that warmer water would reduce the fish population.",
    ["hypothesis", "proof", "law only", "opinion only"], 0),
  e("do-habitat", "habitat", "natural environment of an organism", "domain",
    "Loss of wetland _____ threatens several migratory bird species.",
    ["habitat", "costume", "hobby", "language"], 0),
  e("do-terrestrial", "terrestrial", "of or on land (vs. aquatic/space)", "domain",
    "_____ ecosystems respond differently to drought than aquatic ones do.",
    ["Terrestrial", "Mythical", "Foreign", "Musical"], 0),
  e("do-catalyst", "catalyst", "something that speeds a change (chem. or fig.)", "domain",
    "The scandal acted as a _____ for broader reforms in the agency.",
    ["catalyst", "obstacle", "summary", "decoration"], 0),
  e("do-variable", "variable", "factor that can change in an experiment", "domain",
    "Researchers controlled every _____ except hours of sleep.",
    ["variable", "constant only", "opinion", "location only"], 0),
  e("do-sovereignty", "sovereignty", "supreme authority of a state", "domain",
    "The treaty raised questions about national _____ over coastal resources.",
    ["sovereignty", "decoration", "weather", "grammar"], 0),
  e("do-ideology", "ideology", "system of ideas and ideals", "domain",
    "The party's _____ shaped its stance on education funding.",
    ["ideology", "furniture", "melody", "diet"], 0),
  e("do-disparity", "disparity", "a great difference", "domain",
    "The report highlights a growing _____ in life expectancy between regions.",
    ["disparity", "similarity", "celebration", "agreement"], 0),
  e("do-autonomy", "autonomy", "self-government; independence", "domain",
    "Universities argued for greater _____ in setting admissions criteria.",
    ["autonomy", "obedience", "funding only", "silence"], 0),
  e("do-indigenous", "indigenous", "originating in a particular place", "domain",
    "The park protects plants _____ to the high desert.",
    ["indigenous", "imported", "extinct only", "decorative"], 0),
  e("do-demographic", "demographic", "relating to population structure", "domain",
    "_____ shifts, including an aging population, will reshape demand for healthcare.",
    ["Demographic", "Geological", "Musical", "Literary only"], 0),
  e("do-rhetoric", "rhetoric", "persuasive language (or empty speech)", "domain",
    "The campaign's _____ emphasized unity more than specific policy details.",
    ["rhetoric", "geometry", "silence", "budget only"], 0),
  e("do-paradigm", "paradigm", "typical example or model of thought", "domain",
    "New evidence forced a shift in the prevailing scientific _____.",
    ["paradigm", "building", "melody", "costume"], 0),
  e("do-motif", "motif", "recurring theme or idea", "domain",
    "Isolation is a central _____ throughout the novel's three sections.",
    ["motif", "error", "budget", "accident"], 0),
  e("do-satire", "satire", "use of humor/irony to criticize", "domain",
    "The play uses _____ to expose corruption in local politics.",
    ["satire", "biography only", "manual", "sermon only"], 0),
];

export const VOCAB_BY_ID: Record<string, VocabEntry> = Object.fromEntries(
  VOCAB_BANK.map((w) => [w.id, w]),
);

export function listCategories(): { id: VocabCategory; label: string; count: number }[] {
  const counts = new Map<VocabCategory, number>();
  for (const w of VOCAB_BANK) {
    counts.set(w.category, (counts.get(w.category) ?? 0) + 1);
  }
  const labels = {
    argument: "Argument & evidence",
    analysis: "Analysis & evaluation",
    tone: "Tone & attitude",
    change: "Change & development",
    importance: "Importance & value",
    description: "Description",
    precision: "Precision & rigor",
    transitions: "Transitions",
    "multi-meaning": "Multiple meanings",
    domain: "Domain (science / social)",
  } as const;
  return (Object.keys(labels) as VocabCategory[]).map((id) => ({
    id,
    label: labels[id],
    count: counts.get(id) ?? 0,
  }));
}
